name: CI
on:
  push:
    branches: [ test ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
     - name: Log the step container node version
       uses: docker://rockylinux:9.1
       with:
         entrypoint: usr/bin/uname
         args: -a
