name: CI
on:
  push:
    branches: [ test ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
