name: CI
on:
  push:
    branches: [ test ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
     - name: Log the step container node version
       uses: docker://node:12.14.1-alpine3.1
       with:
         entrypoint: usr/local/bin/echo
         args: -v
