
name: containers-demo

on:
  push:
    branches: [ "service" ]
  pull_request:
    branches: [ "main" ]

jobs:
  info:

    runs-on: ubuntu-latest
    services:
      db-service:  
        image: quay.io/techupskills2/roar-db:v4
        env:
          MYSQL_USER: admin
          MYSQL_PASSWORD: admin
          MYSQL_DATABASE: registry
          MYSQL_ROOT_PASSWORD: root+1
        ports:
          - 3306:3306
    steps:
      - name: get info
        run: ls -la
      - name: get data
        run: mysql -uadmin -padmin -e 'select * from registry.agents'

