
name: containers-demo

on:
  push:
    branches: [ "xmllint" ]
  pull_request:
    branches: [ "xmllint" ]

jobs:
  lint-tool:

    runs-on: ubuntu-latest
    container: 
      image: quay.io/techupskills2/xmltools:1.0.0
     # credentials:
     #   username: ${{ secrets.QUAYIO_ROBOT_USER }}
     #   password: ${{ secrets.QUAYIO_ROBOT_TOKEN }}
   
    steps:
      - name: run xmllint
        run: xmllint
             

