
name: containers-demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  info:

    runs-on: ubuntu-latest
    container: alpine:3.7.3
    steps:
    - uses: actions/checkout@v3
    - name: Build with Gradle
      run: "uname -a"

