
name: containers-demo

on:
  push:
    branches: [ "xmllint" ]
  pull_request:
    branches: [ "xmllint" ]

jobs:
  lint-tool:

    runs-on: ubuntu-latest
    container: 
      image: quay.io/techupskills/roardebug:1.0.2 
      credentials:
        username: ${{ secrets.QUAYIO_USERNAME }}
        password: ${{ secrets.QUAYIO_PASSWORD }}
   
    steps:
      - name: run xmllint
        run: xmllint
             

