
name: containers-demo

on:
  push:
    branches: [ "docker-run" ]
  pull_request:
    branches: [ "main" ]

jobs:
  info:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build with gradle
      run: docker run --rm -u gradle -v "$PWD":/home/gradle/project -w /home/gradle/project gradle gradle 

