name: Unit Test

on:
  push:
    branches: [service2, dev]
  pull_request:
    branches: [master, develop]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ADMIN_PASS }}
          MYSQL_DATABASE: inttests
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" 
                 --health-interval=10s 
                 --health-timeout=5s 
                 --health-retries=3

    steps:
      - uses: actions/checkout@v3  
      - name: Verify integration tests db exists
        run: mysql --host 127.0.0.1 --port 3306 
         -u${{ secrets.MYSQL_USER }} 
         -p${{ secrets.MYSQL_ADMIN_PASS }}
         -e "SHOW DATABASES LIKE 'inttests'"
      
