
name: containers-demo

on:
  push:
    branches: [ "docker-run" ]
  pull_request:
    branches: [ "main" ]

jobs:
  info:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build with gradle
      run: sudo docker run --rm -v "$PWD":/workdir -w /workdir centos:latest ls -laR

