
name: containers-demo

on:
  push:
    branches: [ "xmllint2" ]
  pull_request:
    branches: [ "xmllint2" ]

jobs:
  lint-tool:

    runs-on: ubuntu-latest
     
    steps:
      - uses: actions/checkout@v3
      - name: run xmllint
        uses: docker://bclaster/xmltools:1.0.0
        with:
          entrypoint: xmllint
          args: web.xml     
             

