
name: containers-demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  info:

    runs-on: ubuntu-latest
    container: golang:1.17.0-alpine
    steps:
    - uses: actions/checkout@v3
    - name: get info
      run: "go version"

